"""First migration

Revision ID: e91562e47193
Revises: 
Create Date: 2023-05-07 07:14:09.990804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e91562e47193'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('usersettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hue_index', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usersettings_id'), 'usersettings', ['id'], unique=False)
    op.create_table('huebridges',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('user_settings_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_settings_id'], ['usersettings.id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_huebridges__id'), 'huebridges', ['_id'], unique=False)
    op.create_index(op.f('ix_huebridges_id'), 'huebridges', ['id'], unique=False)
    op.create_table('wleditems',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_settings_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_settings_id'], ['usersettings.id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_wleditems__id'), 'wleditems', ['_id'], unique=False)
    op.create_index(op.f('ix_wleditems_ip'), 'wleditems', ['ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wleditems_ip'), table_name='wleditems')
    op.drop_index(op.f('ix_wleditems__id'), table_name='wleditems')
    op.drop_table('wleditems')
    op.drop_index(op.f('ix_huebridges_id'), table_name='huebridges')
    op.drop_index(op.f('ix_huebridges__id'), table_name='huebridges')
    op.drop_table('huebridges')
    op.drop_index(op.f('ix_usersettings_id'), table_name='usersettings')
    op.drop_table('usersettings')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
